services:
  db:
    image: postgres:16-alpine
    container_name: time_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apprandompass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: time_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://appuser:apprandompass@db:5432/appdb
      PORT: "3000"
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: time_pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
